/* ClassNew.cpp 
*/
#include <iostream>
using namespace std;

class CTest
{
    int m_nData;

public:
    CTest()
    {
        cout << "CTest::CTest()" << endl;
    }

    ~CTest()
    {
        cout << "~CTest::CTest()" << endl;
    }
};

int main(int argc, char* argv[])
{
    cout << "Begin" << endl;

    // generate dynamic object with "new" operator
    // CTest *pData = new CTest;
    // if it is generated by array, then it also should be deleted by array (see below)
    CTest *pData = new CTest[3];
    cout << "Test" << endl;

    // must be deleted by "delete"
    // delete pData;
    delete [] pData;
    cout << "End" << endl;

    return 0;
}



